In [1]:
print("hello wec")

hello wec


first thing is importing the data 
i have chosen the movielens data 
let see how the data looks

In [2]:
import pandas as pd
df = pd.read_csv(
    'ml-100k/u.data', 
    sep='\t', 
    header=None, 
    names=['user_id', 'item_id', 'rating', 'timestamp']
)

In [3]:
df
nousers = df["user_id"].nunique()
nomovies  = df["item_id"].nunique()

checking the data

In [4]:
df.head()
# df.tail()
df.isnull().sum() # so there are no null values 
df.shape

(100000, 4)

In [5]:
user_item_matrix = df.pivot(index='user_id', columns='item_id', values='rating').fillna(0)
# print(user_item_matrix.shape) 
# print(user_item_matrix.head())
user_item_matrix.head()

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


what the above tabel means is that on one user id or a user how many movies it has watched and rated and rating 0 means it hasent seen or rated on it 



In [6]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df,test_size=0.2, random_state=42)
train_data
# test_data


,user_id,item_id,rating,timestamp
75220,807,1411,1,893082619
48955,474,659,5,887925187
44966,463,268,4,877384940
13568,139,286,4,879537844
92727,621,751,4,883799651
...,...,...,...,...
6265,216,231,2,880245109
54886,343,276,5,876403078
76820,437,475,3,880140288
860,284,322,3,885329671


In [7]:
train_user_item_matrix = train_data.pivot(index='user_id', columns='item_id', values='rating').fillna(0)

In [8]:
train_user_item_matrix
# test_data


item_id,1,2,3,4,5,6,7,8,9,10,...,1668,1670,1671,1672,1673,1676,1678,1679,1680,1681
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,3.0,4.0,0.0,3.0,0.0,4.0,0.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [9]:
from sklearn.metrics.pairwise import cosine_similarity
# now we compute the cosine simlarity matrix  be each users 
cosine_sim_matrix = cosine_similarity(train_user_item_matrix)

In [10]:
cosine_sim_matrix.shape
type(cosine_sim_matrix) 
train_user_item_matrix.index
cosine_sim_matrix
cosine_sim_df = pd.DataFrame(
    cosine_sim_matrix, 
    index=train_user_item_matrix.index, 
    columns=train_user_item_matrix.index
)
cosine_sim_df.head()

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.136196,0.030424,0.026203,0.284613,0.331412,0.319056,0.274139,0.083486,0.281396,...,0.277459,0.084849,0.205849,0.144161,0.133679,0.092367,0.216948,0.084181,0.104599,0.329288
2,0.136196,1.000000,0.114644,0.168220,0.093128,0.162165,0.095848,0.091360,0.149476,0.125701,...,0.149359,0.268977,0.320095,0.323347,0.241012,0.152655,0.230951,0.117484,0.166632,0.096719
3,0.030424,0.114644,1.000000,0.346894,0.000000,0.085071,0.032829,0.053875,0.060177,0.052552,...,0.021713,0.017707,0.154299,0.049358,0.107604,0.019022,0.101207,0.021959,0.127179,0.013805
4,0.026203,0.168220,0.346894,1.000000,0.011848,0.051287,0.075209,0.142100,0.060465,0.035202,...,0.034908,0.044480,0.087428,0.118082,0.100612,0.000000,0.151086,0.110324,0.112342,0.032367
5,0.284613,0.093128,0.000000,0.011848,1.000000,0.168527,0.298438,0.185290,0.039737,0.166013,...,0.276012,0.103529,0.085547,0.072429,0.104445,0.049198,0.204472,0.148028,0.099978,0.247527


In [11]:
#now lets do for the pearson so we have two methods to find the relation bw the users to predict the rating
pearson_sim_df = train_user_item_matrix.T.corr(method='pearson', min_periods=1).fillna(0)

In [12]:
pearson_sim_df
# pearson_sim_df.shape
# so now both are done 

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.088475,-0.021909,-0.010971,0.216604,0.254853,0.204153,0.233354,0.055869,0.204544,...,0.203412,0.042700,0.131358,0.105430,0.066620,0.049274,0.154905,0.054101,0.042240,0.263153
2,0.088475,1.000000,0.092622,0.153687,0.053788,0.120272,0.029460,0.065653,0.136981,0.084014,...,0.110464,0.253015,0.292347,0.308313,0.214169,0.133484,0.202912,0.103340,0.139773,0.056219
3,-0.021909,0.092622,1.000000,0.336313,-0.041339,0.041193,-0.036811,0.028702,0.046925,0.009439,...,-0.021407,-0.002592,0.120872,0.029363,0.077722,-0.001897,0.070135,0.007010,0.100743,-0.028335
4,-0.010971,0.153687,0.336313,1.000000,-0.017156,0.019076,0.031394,0.126095,0.050942,0.004094,...,0.004959,0.030401,0.061997,0.104887,0.079556,-0.015220,0.130993,0.100604,0.093502,0.003239
5,0.216604,0.053788,-0.041339,-0.017156,1.000000,0.096456,0.212987,0.147800,0.016232,0.098196,...,0.219438,0.071709,0.019909,0.038569,0.051172,0.013783,0.155633,0.127049,0.051829,0.190599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.049274,0.133484,-0.001897,-0.015220,0.013783,0.027241,0.004581,0.072237,0.047986,-0.025599,...,0.002503,0.298261,0.153723,0.181776,0.322324,1.000000,0.039990,0.144039,-0.004748,0.097808
940,0.154905,0.202912,0.070135,0.130993,0.155633,0.221977,0.224720,0.128495,0.074801,0.240237,...,0.217000,0.035971,0.089714,0.104589,0.010704,0.039990,1.000000,0.066519,0.188940,0.167567
941,0.054101,0.103340,0.007010,0.100604,0.127049,0.101787,-0.018663,0.065738,0.134245,0.041674,...,0.010310,0.190911,0.180634,0.225381,0.178285,0.144039,0.066519,1.000000,0.079141,0.092390


In [13]:
# now making a funtion for to predict 
test_data
# 1. what if  the users is not  there on the trainng set so we cant compute its neighbours
#2.

,user_id,item_id,rating,timestamp
75721,877,381,4,882677345
80184,815,602,3,878694269
19864,94,431,4,891721716
76699,416,875,2,876696938
92991,500,182,2,883873556
...,...,...,...,...
32595,72,591,5,880035708
29313,523,393,5,883702411
37862,606,287,4,880921656
53421,650,612,4,891369656


In [14]:
def predicition(user, item,df,k):
    if (item in df.columns) and (user in df.index):
        checkrows = df[(df[item] > 0) & (df.index != user)]
        has_greater_than_zero = len(checkrows) > 0
        if has_greater_than_zero==True :
            resultpearson = pearson_sim_df.loc[pearson_sim_df.index.isin(checkrows.index), [user]].sort_values(by=user, ascending=False)
            resultcosine = cosine_sim_df.loc[cosine_sim_df.index.isin(checkrows.index), [user]].sort_values(by=user, ascending=False)
            topp = resultpearson.head(k)
            topc = resultcosine.head(k)
            avgpearson = df.reindex(topp.index)[item].mean()
            avgcosine = df.reindex(topc.index)[item].mean()
            return [avgpearson,avgcosine]
        else :
            print("this movie ist rated by any ppl so there will not be any")
            return None
    else :
        print("check ur users or item ")
        return None

def error(pearsoncosine,user,item,test_data ):
    personr = pearsoncosine[0]
    cosiner = pearsoncosine[1]
    actual = test_data.loc[(test_data['user_id'] == user) & (test_data['item_id'] == item), 'rating'].iloc[0]
    return [(personr - actual) ** 2, (cosiner - actual) ** 2]

In [15]:
# train_user_item_matrix.shape
# train_user_item_matrix
# test_data

In [16]:
# user = 4
# checkrows = train_user_item_matrix[(train_user_item_matrix[7] > 0) & (train_user_item_matrix.index != user)]
# resultpearson = pearson_sim_df.loc[pearson_sim_df.index.isin(checkrows.index), [user]].sort_values(by=user, ascending=False)
# resultcosine = cosine_sim_df.loc[cosine_sim_df.index.isin(checkrows.index), [user]].sort_values(by=user, ascending=False)

In [17]:
# resultpearson


In [18]:
# resultcosine

In [19]:
import numpy as np
a =[2,3,5,10 , 20 , 30 ,40 ]
for val in a :
    k = val
    sqerr_pearson = []
    sqerr_cosine = []
    for user, item in zip(test_data['user_id'], test_data['item_id']):
        pearsoncosine = predicition(user, item, train_user_item_matrix, k)
        if pearsoncosine is None:
            continue
        sp, sc = error(pearsoncosine, user, item, test_data)
        sqerr_pearson.append(sp)
        sqerr_cosine.append(sc)
    rmse_pearson = np.sqrt(np.mean(sqerr_pearson))
    rmse_cosine = np.sqrt(np.mean(sqerr_cosine))
    print(f"for k = {val} the errors are given below  ")
    print(f"pearson RMSE = {rmse_pearson}")
    print(f"cosine RMSE = {rmse_cosine}")
    print(f"test rows used = {len(sqerr_pearson)} out of {len(test_data)}")

check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
for k = 2 the errors are given below  
pearson RMSE = 1.1755389965864032
cosine RMSE = 1.1683549686057024
test rows used = 19969 out of 20000
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or item 
check ur users or 

now lets build the matrix model 

In [20]:
import pandas as pd 
import numpy as np
train_data


,user_id,item_id,rating,timestamp
75220,807,1411,1,893082619
48955,474,659,5,887925187
44966,463,268,4,877384940
13568,139,286,4,879537844
92727,621,751,4,883799651
...,...,...,...,...
6265,216,231,2,880245109
54886,343,276,5,876403078
76820,437,475,3,880140288
860,284,322,3,885329671


now making the matrix factorization model 

In [21]:
df

,user_id,item_id,rating,timestamp
0,196,242,3,881250949
1,186,302,3,891717742
2,22,377,1,878887116
3,244,51,2,880606923
4,166,346,1,886397596
...,...,...,...,...
99995,880,476,3,880175444
99996,716,204,5,879795543
99997,276,1090,1,874795795
99998,13,225,2,882399156


In [22]:
train_data
df.shape
df

nomovies
nousers
train_data

,user_id,item_id,rating,timestamp
75220,807,1411,1,893082619
48955,474,659,5,887925187
44966,463,268,4,877384940
13568,139,286,4,879537844
92727,621,751,4,883799651
...,...,...,...,...
6265,216,231,2,880245109
54886,343,276,5,876403078
76820,437,475,3,880140288
860,284,322,3,885329671


In [23]:
import numpy as np 

np.random.seed(42)
k = 10 


unique_users = train_data['user_id'].unique()
unique_items = train_data['item_id'].unique()

user_to_idx = {raw_id: i for i, raw_id in enumerate(unique_users)}
item_to_idx = {raw_id: i for i, raw_id in enumerate(unique_items)}
train_array = np.array([
    [user_to_idx[row.user_id], item_to_idx[row.item_id], row.rating]
    for row in train_data.itertuples()
])
P = np.random.randn(nousers, k) / np.sqrt(k)   
Q = np.random.randn(nomovies, k) / np.sqrt(k)   

           
# R_pred = P @ Q.T        
print(P.shape, Q.shape)
train_array

(943, 10) (1682, 10)


array([[  0,   0,   1],
       [  1,   1,   5],
       [  2,   2,   4],
       ...,
       [517, 231,   3],
       [268, 222,   3],
       [147,  46,   3]], shape=(80000, 3))

In [24]:
alpha = 0.01
lamb = 0.01
n_epochs = 20

for epoch in range(1, n_epochs + 1):
    print(f"epoch {epoch} starting")
    np.random.shuffle(train_array)            

    total_sq_err = 0

    for row in train_array:
        u = int(row[0])
        i = int(row[1])
        r = row[2]

        p_old = P[u].copy()
        q_old = Q[i].copy()

        pred = p_old @ q_old
        e = r - pred

        P[u] = p_old + 2*alpha*(e*q_old - lamb*p_old)
        Q[i] = q_old + 2*alpha*(e*p_old - lamb*q_old)

        total_sq_err += e**2

    rmse = np.sqrt(total_sq_err / len(train_array))
    print(f"epoch {epoch} ended, train RMSE = {rmse:.4f}")

epoch 1 starting
epoch 1 ended, train RMSE = 2.7004
epoch 2 starting
epoch 2 ended, train RMSE = 1.0835
epoch 3 starting
epoch 3 ended, train RMSE = 0.9682
epoch 4 starting
epoch 4 ended, train RMSE = 0.9267
epoch 5 starting
epoch 5 ended, train RMSE = 0.8998
epoch 6 starting
epoch 6 ended, train RMSE = 0.8794
epoch 7 starting
epoch 7 ended, train RMSE = 0.8631
epoch 8 starting
epoch 8 ended, train RMSE = 0.8486
epoch 9 starting
epoch 9 ended, train RMSE = 0.8355
epoch 10 starting
epoch 10 ended, train RMSE = 0.8260
epoch 11 starting
epoch 11 ended, train RMSE = 0.8164
epoch 12 starting
epoch 12 ended, train RMSE = 0.8082
epoch 13 starting
epoch 13 ended, train RMSE = 0.8015
epoch 14 starting
epoch 14 ended, train RMSE = 0.7949
epoch 15 starting
epoch 15 ended, train RMSE = 0.7894
epoch 16 starting
epoch 16 ended, train RMSE = 0.7851
epoch 17 starting
epoch 17 ended, train RMSE = 0.7804
epoch 18 starting
epoch 18 ended, train RMSE = 0.7768
epoch 19 starting
epoch 19 ended, train RMSE =

In [25]:
test_rows = []
skipped = 0

for row in test_data.itertuples():
    if row.user_id in user_to_idx and row.item_id in item_to_idx:
        test_rows.append([user_to_idx[row.user_id],
                          item_to_idx[row.item_id],
                          row.rating])
    else:
        skipped += 1          

test_array = np.array(test_rows)
print("kept:", len(test_array), "skipped:", skipped)
print(test_array[:5])         

kept: 19969 skipped: 31
[[ 360  347    4]
 [ 144 1015    3]
 [ 150  328    4]
 [ 205  445    2]
 [ 117  201    2]]


In [26]:
def evaluate(arr, P, Q, fallback):
    sq_err = 0

    for row in arr:
        u = int(row[0])
        i = int(row[1])
        r = row[2]

        if u == -1 or i == -1:   # this fall back will not work as i have removed all the rows not in the train set there 31 of them     
            pred = fallback           
        else:
            pred = P[u] @ Q[i]

        sq_err += (r - pred) ** 2

    rmse = np.sqrt(sq_err / len(arr))
    print(f"testing done, rmse = {rmse:.4f}")
    return rmse


global_mean = train_array[:, 2].mean()
test_rmse = evaluate(test_array, P, Q, global_mean)

testing done, rmse = 0.9997
